dds/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dds_service.urls", namespace="dds_service")),
]

dds_service/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from dds_service.apps import DdsServiceConfig

from .views import (CategoryCreateAPIView, CategoryDestroyAPIView,
                    CategoryDetailView, CategoryView, StatusCreateAPIView,
                    StatusDestroyAPIView, StatusDetailView, StatusView,
                    SubCategoryCreateAPIView, SubCategoryDestroyAPIView,
                    SubCategoryDetailView, SubCategoryView,
                    TransactionCreateAPIView, TransactionDestroyAPIView,
                    TransactionDetailView, TransactionView, TypeCreateAPIView,
                    TypeDestroyAPIView, TypeDetailView, TypeView)

router = DefaultRouter()

app_name = DdsServiceConfig.name

urlpatterns = [
    # статус
    path("status/", StatusView.as_view(), name="status"),
    path("status/<int:pk>/", StatusDetailView.as_view(), name="status-detail"),
    path(
        "status/<int:pk>/delete/", StatusDestroyAPIView.as_view(), name="status-delete"
    ),
    path("status/create/", StatusCreateAPIView.as_view(), name="status-create"),
    # тип
    path("type/", TypeView.as_view(), name="type"),
    path("type/<int:pk>/", TypeDetailView.as_view(), name="type-detail"),
    path("type/<int:pk>/delete/", TypeDestroyAPIView.as_view(), name="type-delete"),
    path("type/create/", TypeCreateAPIView.as_view(), name="type-create"),
    # категория
    path("category/", CategoryView.as_view(), name="category"),
    path("category/<int:pk>/", CategoryDetailView.as_view(), name="category-detail"),
    path(
        "category/<int:pk>/delete/",
        CategoryDestroyAPIView.as_view(),
        name="category-delete",
    ),
    path("category/create/", CategoryCreateAPIView.as_view(), name="category-create"),
    # подкатегория
    path("subcategory/", SubCategoryView.as_view(), name="subcategory"),
    path(
        "subcategory/<int:pk>/",
        SubCategoryDetailView.as_view(),
        name="subcategory-detail",
    ),
    path(
        "subcategory/<int:pk>/delete/",
        SubCategoryDestroyAPIView.as_view(),
        name="subcategory-delete",
    ),
    path(
        "subcategory/create/",
        SubCategoryCreateAPIView.as_view(),
        name="subcategory-create",
    ),
    # транзакция
    path("transaction/", TransactionView.as_view(), name="transaction"),
    path(
        "transaction/<int:pk>/",
        TransactionDetailView.as_view(),
        name="transaction-detail",
    ),
    path(
        "transaction/<int:pk>/delete/",
        TransactionDestroyAPIView.as_view(),
        name="transaction-delete",
    ),
    path(
        "transaction/create/",
        TransactionCreateAPIView.as_view(),
        name="transaction-create",
    ),
]

dds_service/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Status(models.Model):
    """Модель для хранений статусов."""

    name = models.CharField(max_length=128, unique=True, verbose_name="Статус")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"


class Type(models.Model):
    """Модель для хранений типов операций."""

    name = models.CharField(max_length=128, unique=True, verbose_name="Тип")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип"
        verbose_name_plural = "Типы"


class Category(models.Model):
    """Модель для хранений категорий."""

    name = models.CharField(max_length=128, unique=True, verbose_name="Категория")
    type = models.ForeignKey(
        Type, on_delete=models.DO_NOTHING, verbose_name="Тип операции"
    )

    def __str__(self):
        return f"{self.name} ({self.type})"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class SubCategory(models.Model):
    """Модель для хранений подкатегорий."""

    name = models.CharField(max_length=128, unique=True, verbose_name="Подкатегория")
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, verbose_name="Категория"
    )

    def __str__(self):
        return f"{self.name} ({self.category})"

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Transaction(models.Model):
    """Модель для хранений движения денежных средств."""

    created_at = models.DateField(verbose_name="Дата создания")

    status = models.ForeignKey(
        Status, on_delete=models.DO_NOTHING, verbose_name="Статус"
    )

    type = models.ForeignKey(Type, on_delete=models.DO_NOTHING, verbose_name="Тип")

    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, verbose_name="Категория"
    )

    subcategory = models.ForeignKey(
        SubCategory, on_delete=models.DO_NOTHING, verbose_name="Подкатегория"
    )

    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Сумма")

    description = models.TextField(blank=True, null=True, verbose_name="Комментарий")

    def __str__(self):
        return f"{self.status}/{self.created_at} - {self.amount} руб."

    def clean(self):
        """
        - Проверка связи подкатегории с категорией
        - Проверка связи категории с типом
        - Проверка, что сумма операции неотрицательная
        """

        super().clean()

        if self.subcategory.category != self.category:
            raise ValidationError(
                {"subcategory": "Подкатегория не связана с выбранной категорией."}
            )

        if self.category.type != self.type:
            raise ValidationError(
                {"category": "Категория не соответствует выбранному типу операции."}
            )

        if self.amount < 0:
            raise ValidationError({"amount": "Сумма не может быть отрицательной"})

    class Meta:
        verbose_name = "Движение денежных средств"
        verbose_name_plural = "Движения денежных средств"
        ordering = ["-created_at"]

dds_service/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters, generics, status, viewsets
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from dds_service.models import Category, Status, SubCategory, Transaction, Type

from .filters import TransactionFilter
from .serializers import (CategorySerializer, StatusSerializer,
                          SubCategorySerializer, TransactionSerializer,
                          TypeSerializer)


# Статусы
class StatusView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "status_list.html"

    def get(self, request):
        queryset = Status.objects.all()
        return Response({"statuses": queryset})


class StatusDetailView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "status_detail.html"

    def get(self, request, pk):
        queryset = get_object_or_404(Status, pk=pk)
        serializer = StatusSerializer(queryset)
        return Response({"serializer": serializer, "obj": queryset})

    def post(self, request, pk):
        queryset = get_object_or_404(Status, pk=pk)
        serializer = StatusSerializer(queryset, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "obj": queryset})
        serializer.save()
        return redirect("/status/")


class StatusDestroyAPIView(generics.DestroyAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "status_delete.html"

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        return Response({"obj": obj})

    def post(self, request, *args, **kwargs):
        self.destroy(request, *args, **kwargs)
        return redirect("/status/")


class StatusCreateAPIView(generics.ListCreateAPIView):
    queryset = Status.objects.all()
    serializer_class = StatusSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "status_create.html"

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect("/status/")
        else:
            return Response({"serializer": serializer})


# Типы
class TypeView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "type_list.html"

    def get(self, request):
        queryset = Type.objects.all()
        return Response({"types": queryset})


class TypeDetailView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "type_detail.html"

    def get(self, request, pk):
        queryset = get_object_or_404(Type, pk=pk)
        serializer = TypeSerializer(queryset)
        return Response({"serializer": serializer, "obj": queryset})

    def post(self, request, pk):
        queryset = get_object_or_404(Type, pk=pk)
        serializer = TypeSerializer(queryset, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "obj": queryset})
        serializer.save()
        return redirect("/type/")


class TypeDestroyAPIView(generics.DestroyAPIView):
    queryset = Type.objects.all()
    serializer_class = TypeSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "type_delete.html"

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        return Response({"obj": obj})

    def post(self, request, *args, **kwargs):
        self.destroy(request, *args, **kwargs)
        return redirect("/type/")


class TypeCreateAPIView(generics.ListCreateAPIView):
    queryset = Type.objects.all()
    serializer_class = TypeSerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "type_create.html"

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect("/type/")
        else:
            return Response({"serializer": serializer})


# Категории
class CategoryView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "category_list.html"

    def get(self, request):
        queryset = Category.objects.all()
        return Response({"categories": queryset})


class CategoryDetailView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "category_detail.html"

    def get(self, request, pk):
        queryset = get_object_or_404(Category, pk=pk)
        serializer = CategorySerializer(queryset)
        return Response({"serializer": serializer, "obj": queryset})

    def post(self, request, pk):
        queryset = get_object_or_404(Category, pk=pk)
        serializer = CategorySerializer(queryset, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "obj": queryset})
        serializer.save()
        return redirect("/category/")


class CategoryDestroyAPIView(generics.DestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "category_delete.html"

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        return Response({"obj": obj})

    def post(self, request, *args, **kwargs):
        self.destroy(request, *args, **kwargs)
        return redirect("/category/")


class CategoryCreateAPIView(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "category_create.html"

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect("/category/")
        else:
            return Response({"serializer": serializer})


# Подкатегории
class SubCategoryView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "subcategory_list.html"

    def get(self, request):
        queryset = SubCategory.objects.all()
        return Response({"subcategories": queryset})


class SubCategoryDetailView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "subcategory_detail.html"

    def get(self, request, pk):
        queryset = get_object_or_404(SubCategory, pk=pk)
        serializer = SubCategorySerializer(queryset)
        return Response({"serializer": serializer, "obj": queryset})

    def post(self, request, pk):
        queryset = get_object_or_404(SubCategory, pk=pk)
        serializer = SubCategorySerializer(queryset, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "obj": queryset})
        serializer.save()
        return redirect("/subcategory/")


class SubCategoryDestroyAPIView(generics.DestroyAPIView):
    queryset = SubCategory.objects.all()
    serializer_class = SubCategorySerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "subcategory_delete.html"

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        return Response({"obj": obj})

    def post(self, request, *args, **kwargs):
        self.destroy(request, *args, **kwargs)
        return redirect("/subcategory/")


class SubCategoryCreateAPIView(generics.ListCreateAPIView):
    queryset = SubCategory.objects.all()
    serializer_class = SubCategorySerializer
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "subcategory_create.html"

    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer()
        return Response({"serializer": serializer})

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect("/subcategory/")
        else:
            return Response({"serializer": serializer})


# Движение денежных средств
class TransactionView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "transaction_list.html"
    filter_backends = [DjangoFilterBackend]
    filterset_class = TransactionFilter

    def get(self, request):
        queryset = Transaction.objects.all()
        filterset = TransactionFilter(request.GET, queryset=queryset)
        return Response({"transactions": filterset.qs})


class TransactionDetailView(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "transaction_detail.html"

    def get(self, request, pk):
        queryset = get_object_or_404(Transaction, pk=pk)
        serializer = TransactionSerializer(queryset)
        return Response({"serializer": serializer, "obj": queryset})

    def post(self, request, pk):
        queryset = get_object_or_404(Transaction, pk=pk)
        serializer = TransactionSerializer(queryset, data=request.data)
        if not serializer.is_valid():
            return Response({"serializer": serializer, "obj": queryset})
        serializer.save()
        return redirect("/transaction/")


class TransactionDestroyAPIView(generics.DestroyAPIView):
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer

dds_service/templates/category_list.html
{% extends 'base.html' %}
{% load rest_framework %}
{% block title %}Категории{% endblock %}

{% block content %}

    <h3>Категории <a class="btn btn-primary ms-3" href="{% url 'dds_service:category-create' %}">Добавить</a></h3>

    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Наименование</th>
                <th></th>
            </tr>
            </thead>

            {% for object in categories %}
                <tbody class="align-text-top">
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td>{{ object.name }}</td>
                    <td>
                        <a href="{% url 'dds_service:category-detail' object.pk %}"
                           class="card-link btn btn-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                <path fill-rule="evenodd"
                                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'dds_service:category-delete' object.pk %}"
                           class="card-link btn btn-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"></path>
                            </svg>
                        </a>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>

{% endblock %}

dds_service/templates/header.html
<ul class="nav nav-tabs ps-5 pe-5 d-flex align-items-center">
    <div class="p-2">
        <a class="navbar-brand text-black-50" href="{% url 'dds_service:transaction' %}">Движение денежных средств</a>
    </div>
    <div>
        <li class="nav-item dropdown">
            <a class="nav-link" href="{% url 'dds_service:transaction' %}">Операции</a>
        </li>
    </div>

    <div class="ms-auto pe-3">
        <li class="nav-item dropdown">
            <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button"
               aria-expanded="false"> Управление справочниками
{#                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"#}
{#                     class="bi bi-gear mb-1" viewBox="0 0 16 16">#}
{#                    <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>#}
{#                    <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>#}
{#                </svg> #}
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item align-items-center" href="{% url 'dds_service:status' %}">Статусы</a></li>
                <li><a class="dropdown-item align-items-center" href="{% url 'dds_service:type' %}">Типы операций</a></li>
                <li><a class="dropdown-item align-items-center" href="{% url 'dds_service:category' %}">Категории</a></li>
                <li><a class="dropdown-item align-items-center" href="{% url 'dds_service:subcategory' %}">Подкатегории</a></li>
            </ul>
        </li>
    </div>
</ul>

dds_service/templates/transaction_list.html
{% extends 'base.html' %}
{% load rest_framework %}

{% block title %}Операции{% endblock %}


{% block content %}

    <form method="get" action="{% url 'dds_service:transaction' %}" class="p-3 border rounded mb-4">

        <div class="row mb-4">

            <div class='col'>
                <label for='date_from' class='form-label'>Дата с</label>
                <input type='date' class='form-control' id='date_from' name='date_from'>
            </div>

            <div class='col'>
                <label for='date_to' class='form-label'>Дата по</label>
                <input type='date' class='form-control' id='date_to' name='date_to'>
            </div>

        </div>

        <hr>

        <div class="row mt-4">

            <div class="col">
                <label for="status" class="form-label">Статус</label>
                <input type="text" class="form-control" id="status" name="status__name"
                       value="{{ request.GET.status__name }}" placeholder="Введите статус">
            </div>

            <div class="col">
                <label for="category" class="form-label">Категория</label>
                <input type="text" class="form-control" id="category" name="category__name"
                       placeholder="Введите категорию" value="{{ request.GET.category__name }}">
            </div>

            <div class='col'>
                <label for='sub_category' class='form-label'>Подкатегория</label>
                <input type='text' class='form-control' id='sub_category' name='subcategory__name'
                       value="{{ request.GET.subcategory__name }}" placeholder='Введите подкатегорию'>
            </div>

        </div>

        <div class='mt-3'>
            <button type='submit' class='btn btn-success'>Применить фильтры</button>
            <button type='reset' class='btn btn-secondary'>Очистить</button>
        </div>
    </form>
    <h3>Операции <a class="btn btn-primary ms-3" href="{% url 'dds_service:transaction-create' %}">Добавить</a></h3>

    <div class="row">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Дата создания</th>
                <th scope="col">Статус</th>
                <th scope="col">Тип</th>
                <th scope="col">Категория</th>
                <th scope="col">Подкатегория</th>
                <th scope="col">Сумма</th>
                <th scope="col">Комментарий</th>
                <th></th>
            </tr>
            </thead>

            {% for object in transactions %}
                <tbody class="align-text-top">
                <tr>
                    <th scope="row">{{ object.pk }}</th>
                    <td>{{ object.created_at }}</td>
                    <td>{{ object.status }}</td>
                    <td>{{ object.type }}</td>
                    <td>{{ object.category.name }}</td>
                    <td>{{ object.subcategory.name }}
                    <td>{{ object.amount }} руб.</td>
                    <td>{{ object.description|truncatechars:20 }}</td>
                    <td>
                        <a href="{% url 'dds_service:transaction-detail' object.pk %}"
                           class="card-link btn btn-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                <path fill-rule="evenodd"
                                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'dds_service:transaction-delete' object.pk %}"
                           class="card-link btn btn-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"></path>
                            </svg>
                        </a>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
    </div>
{% endblock %}